### ISSUE TITLE
utf 8 error

### ISSUE THREAD

**Issue by suprohub** [JulianSchmid/etherparse#107]
when i try print in string i get this error
called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 8, 0, 69, 0, 0, 44, 0, 0, 64, 0, 20, 6, 104, 35, 192, 168, 88, 81, 64, 233, 164, 198, 200, 124, 1, 187, 0, 0, 48, 57, 0, 0, 0, 0, 80, 0, 15, 160, 167, 38, 0, 0, 0, 0, 0, 0], error: Utf8Error { valid_up_to: 26, error_len: Some(1) } }

**Comment by JulianSchmid** [comment]
Hi can you please clarify a bit more?

**Comment by JulianSchmid** [comment]
I will close the ticket for now. Please open another ticket with a more in depth description (e.g. minimal example code) how you go that error. Then I might be able to help.
