### ISSUE TITLE
How to build TCP and raw ethernet packet by using Builder?

### ISSUE THREAD

**Issue by astrojhgu** [JulianSchmid/etherparse#2]
From the document, I know that PacketBuilderStep has a ```write``` method to dump raw bytes for UDP packet, but no such method for TCP or Ethernet packet.

How to build packets other than UDP with the builder? Or maybe will be supported in the future?

Thanks.

**Comment by JulianSchmid** [comment]
Hi,

It is currently not possible to build TCP packets with the packet builder. I started implementing this feature, but have not finished yet (see "Roadmap" in the Readme). If everything goes according to plan it should be done in 1-2 weeks.

Greets
Julian

**Comment by JulianSchmid** [comment]
I added support for building TCP packets to the latest release 0.7.0. Check out the example in examples/write_tcp.rs for more informations.

**Comment by astrojhgu** [comment]
Thank you @JulianSchmid
