### ISSUE TITLE
etherparse 0.12.0 should have been etherparse 0.11.1

### ISSUE THREAD

**Issue by nox** [JulianSchmid/etherparse#36]
The only changes in etherparse in 0.12.0 are new APIs, which are backwards-compatible changes.

Cargo follows semver, with the added rule that 0.y.z+1 is compatible with 0.y.z.

If the rules are followed, that means less bumps for downstream users, which is nice.

https://doc.rust-lang.org/cargo/reference/semver.html

> This guide uses the terms "major" and "minor" assuming this relates to a "1.0.0" release or later. Initial development releases starting with "0.y.z" can treat changes in "y" as a major release, and "z" as a minor release. "0.0.z" releases are always major changes. This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

**Comment by JulianSchmid** [comment]
Will keep that in mind for upcoming version.
