### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [JulianSchmid/etherparse#41]
I'm trying to use custom udp packet builder with almost same code:
https://github.com/JulianSchmid/etherparse/blob/master/examples/write_ipv4_udp.rs

some context to show the error later
```rust
//setup the actual payload of the udp packet
let udp_payload = [1,2,3,4,5,6,7,8];

//source ip address
[192,168,1,42],
//destination ip address
[192,168,1,1]
```

```
$ cargo run --example=write_ipv4_udp
[1, 2, 3, 4, 5, 6, 11, 12, 13, 14, 15, 16, 8, 0, 69, 0, 0, 36, 0, 0, 64, 0, 20, 17, 227, 77, 192, 168, 1, 42, 192, 168, 1, 1, 0, 0, 0, 42, 0, 16, 108, 20]
```

IPv4: (start from 0x45/69)
```
[69, 0, 0, 36, 0, 0, 64, 0, 20, 17, 227, 77, 192, 168, 1, 42, 192, 168, 1, 1, 0, 0, 0, 42, 0, 16, 108, 20]
```

I'm using raw sockets to send it and Wireshark to view packets
![image1](https://user-images.githubusercontent.com/109800286/208246046-68c42f14-bfc5-45f4-8a58-95e4ba4f6699.png)
software shows that UDP packet is invalid
![image2](https://user-images.githubusercontent.com/109800286/208246171-c4736af3-e0a7-47fd-9b93-a604fcbaa2dd.png)

payload length is calculated as `udp_header_len + payload.len() = 8 + 8 = 16` 
but as we see there is no `payload` at the generated packet

**Comment by JulianSchmid** [comment]
Good catch & thanks for the fix.
