### ISSUE TITLE
Why is ip_payload_ref optional?

### ISSUE THREAD

**Issue by pronebird** [JulianSchmid/etherparse#89]
Hi,

Noticed today that `NetSlice::ip_payload_ref()` returns `Option<&IpPayloadSlice<'a>>` but can't really figure out the reason why because it seems that both IPv4/6 have payload. Is it some smart trick or a genuine omission?

```rs
impl<'a> NetSlice<'a> {
    /// Returns a reference to ip payload if the net slice contains
    /// an ipv4 or ipv6 slice.
    #[inline]
    pub fn ip_payload_ref(&self) -> Option<&IpPayloadSlice<'a>> {
        match self {
            NetSlice::Ipv4(s) => Some(&s.payload),
            NetSlice::Ipv6(s) => Some(&s.payload),
        }
    }
}
```

**Comment by JulianSchmid** [comment]
Hi @pronebird ,

I made it an optional, as ARP might be added as a value to `NetSlice` in the future (see https://github.com/JulianSchmid/etherparse/issues/81 for more details).

Greets
Julian

**Comment by pronebird** [comment]
Got it. Thanks
