### ISSUE TITLE
Atempting to compile in a no_std crate results in an error with Sum16BitWords

### ISSUE THREAD

**Issue by DeepHorizons** [JulianSchmid/etherparse#93]
Hello, I'm trying to compile `etherparse` 0.14.2 in a `no_std` crate but im getting errors about `add_2bytes` (among others) not existing.

```
cargo build
   Compiling etherparse v0.14.2
error[E0599]: no method named `add_2bytes` found for struct `Sum16BitWords` in the current scope
   --> /home/josh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/etherparse-0.14.2/src/net/ipv4_header.rs:648:14
    |
647 | /         checksum::Sum16BitWords::new()
648 | |             .add_2bytes([
    | |_____________-^^^^^^^^^^
    |
   ::: /home/josh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/etherparse-0.14.2/src/checksum.rs:4:1
    |
4   |   pub struct Sum16BitWords {
    |   ------------------------ method `add_2bytes` not found for this struct
    |
help: there is a method `add_16bytes` with a similar name
    |
648 |             .add_16bytes([
    |              ~~~~~~~~~~~

...

rror[E0560]: struct `Sum16BitWords` has no field named `sum`
  --> /home/josh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/etherparse-0.14.2/src/checksum.rs:16:25
   |
16 |         Sum16BitWords { sum: 0 }
   |                         ^^^ `Sum16BitWords` does not have this field
   |
   = note: all struct fields are already assigned


```

**Comment by JulianSchmid** [comment]
Hi @DeepHorizons ,

I will have a look in a few days what the issue is.

Greets
Julian

**Comment by DeepHorizons** [comment]
@JulianSchmid 

I have a sample repo here: https://github.com/DeepHorizons/rust-attiny85-etherparse-test

I am trying to compile for the AVR arch, ultimate goal is to target the ATTiny85 and ATTiny404 but im just trying to get it to work on an Arduino first. It is an 8-bit platform.

**Comment by JulianSchmid** [comment]
Thanks for the sample repo, I could reproduce the error. So far I only tested 64 & 32 bit systems. I will have a look if I can at least partially support the platform.

Is there something specifically you want to use the crate for?

**Comment by DeepHorizons** [comment]
I'm looking at using the crate for parsing udp data grams, over ipv6
packets, over Ethernet frames. Focus will be on DHCP.

Thanks for looking into this!

**Comment by JulianSchmid** [comment]
I released the fix as part of https://github.com/JulianSchmid/etherparse/releases/tag/v0.14.3
